site:
  title: My OpenSource // Docs
  start_page: jooqx::index.adoc
  url: https://zero88.github.io/webdocs
  robots: allow
content:
  sources:
    - url: https://github.com/zero88/jooqx
      start_paths: antora/jooqx
      branches:
        - docs/main
      tags:
        - docs/jooqx/v*
    - url: https://github.com/zero88/jooqx
      start_paths: antora/rsql
      branches:
        - docs/main
      tags:
        - docs/rsql/v*
    - url: https://github.com/zero88/beanx
      start_paths: antora/beanx
      branches:
        - docs/main
      tags:
        - docs/beanx/v*
    - url: https://github.com/zero88/scheduler.x
      start_paths: antora/schedulerx
      branches:
        - docs/main
      tags:
        - docs/schedulerx/v*
asciidoc:
  attributes:
    page-simple-icons-cdn: https://cdn.jsdelivr.net/npm/simple-icons@v11/icons
    page-docsearch-cdn: https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn
    page-lunr-cdn: https://cdn.jsdelivr.net/npm/lunr@2.3.9/lunr.min.js
    page-lunr-lang-cdn: https://cdn.jsdelivr.net/npm/lunr-languages@1.9.0/lunr.stemmer.support.js
    kroki-fetch-diagram: true
    kroki-default-format: png@
  extensions:
    - asciidoctor-kroki
antora:
  extensions:
    - "@antora/lunr-extension"
runtime:
  log:
    level: all
    format: pretty
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./build
  clean: true
