name: webdocs

on:
  workflow_dispatch:
    inputs:
      docCommitMsg:
        description: 'CI message'
        default: 'Build webdocs'
        required: true

jobs:
  site:
    name: Build and Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout webdocs
        uses: actions/checkout@v3
        with:
          ref: main
          path: webdocs

      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.OSS_GITHUB_TOKEN }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: false
          git_push_gpgsign: false
          gpg_private_key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.CI_GPG_PASSPHARSE }}
          workdir: gh-pages

      - uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Build webdocs
        shell: bash
        run: |
          cd webdocs
          yarn install
          yarn antora --fetch antora-playbook.yml --stacktrace

      - name: Sync changes to Git branch [gh-pages]
        shell: bash
        run: |
          rm -rf gh-pages/docs \
            && mkdir -p gh-pages/docs \
            && cp -rf webdocs/build/* webdocs/build/.[^.]* gh-pages/docs
          cd gh-pages
          git add .
          git diff-index --quiet HEAD || git commit -am "${{ inputs.docCommitMsg }}"
          git push -u origin gh-pages
